# Generated by Django 3.0.7 on 2021-04-07 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210305_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoceanuser',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Company registration address'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=29, validators=[django.core.validators.RegexValidator(message='Wrong IBAN format', regex='^[A-Za-z]{2}\\d{27}$')], verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='identification_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='EDRPOU/ITN'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='mfo',
            field=models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator(message='This field must contain 6 characters, only numbers', regex='^\\d{6}$')], verbose_name='MFO'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='person_status',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('individual_entrepreneur', 'Individual entrepreneur'), ('legal_entity', 'Legal entity')], default='individual', max_length=23),
        ),
    ]
